apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask01
  template:
    metadata:
      labels:
        app: flask01
    spec:
      containers:
      - name: flask01
        image: <your-acr-name>.azurecr.io/flask01:latest
        ports:
        - containerPort: 80
