name: Deploy AKS Cluster and Application

on:
  push:
    branches:
      - trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: Terraform Init
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          
      - name: Terraform Plan
        run: terraform plan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      - name: Post Apply Output
        id: output
        run: terraform output -json > output.json
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      - name: Read Terraform Outputs
        id: read-output
        run: |
          echo "RESOURCE_GROUP=$(jq -r '.resource_group_name.value' output.json)"
          echo "AKS_CLUSTER=$(jq -r '.aks_cluster_name.value' output.json)"
          echo "RESOURCE_GROUP=$(jq -r '.resource_group_name.value' output.json)" >> $GITHUB_ENV
          echo "AKS_CLUSTER=$(jq -r '.aks_cluster_name.value' output.json)" >> $GITHUB_ENV

      - name: Install Kubectl
        run: |
          az aks install-cli
          az aks get-credentials --overwrite-existing \
            --name ${{ env.AKS_CLUSTER }} \
            --resource-group ${{ env.RESOURCE_GROUP }}

      - name: Verify kubectl installation
        run: kubectl version --client

      - name: Deploy Sample Application
        run: |
          kubectl apply -f k8s/deployment.yml
          kubectl apply -f k8s/service.yml
