name: Deploy Application to AKS

on:
  workflow_run:
    workflows: ["Deploy AKS Cluster"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          az login --service-principal \
            --username "${ARM_CLIENT_ID}" \
            --password "${ARM_CLIENT_SECRET}" \
            --tenant "${ARM_TENANT_ID}"
          az account set --subscription "${ARM_SUBSCRIPTION_ID}"

      - name: Install Kubectl
        run: |
          az aks install-cli
          echo "RESOURCE_GROUP=$RESOURCE_GROUP" >> $GITHUB_ENV
          echo "AKS_CLUSTER=$AKS_CLUSTER" >> $GITHUB_ENV
          az aks get-credentials --overwrite-existing \
            --name $AKS_CLUSTER \
            --resource-group $RESOURCE_GROUP

      - name: Deploy Application
        run: |
          kubectl apply -f k8s/deployment.yml
          kubectl apply -f k8s/service.yml
